/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsRoomRouteImport } from './routes/rooms/$room'
import { Route as ApiRoomsRoomEventsRouteImport } from './routes/api/rooms/$room/events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomRoute = RoomsRoomRouteImport.update({
  id: '/rooms/$room',
  path: '/rooms/$room',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoomEventsRoute = ApiRoomsRoomEventsRouteImport.update({
  id: '/api/rooms/$room/events',
  path: '/api/rooms/$room/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rooms/$room': typeof RoomsRoomRoute
  '/api/rooms/$room/events': typeof ApiRoomsRoomEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rooms/$room': typeof RoomsRoomRoute
  '/api/rooms/$room/events': typeof ApiRoomsRoomEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rooms/$room': typeof RoomsRoomRoute
  '/api/rooms/$room/events': typeof ApiRoomsRoomEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rooms/$room' | '/api/rooms/$room/events'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rooms/$room' | '/api/rooms/$room/events'
  id: '__root__' | '/' | '/rooms/$room' | '/api/rooms/$room/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomsRoomRoute: typeof RoomsRoomRoute
  ApiRoomsRoomEventsRoute: typeof ApiRoomsRoomEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$room': {
      id: '/rooms/$room'
      path: '/rooms/$room'
      fullPath: '/rooms/$room'
      preLoaderRoute: typeof RoomsRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$room/events': {
      id: '/api/rooms/$room/events'
      path: '/api/rooms/$room/events'
      fullPath: '/api/rooms/$room/events'
      preLoaderRoute: typeof ApiRoomsRoomEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomsRoomRoute: RoomsRoomRoute,
  ApiRoomsRoomEventsRoute: ApiRoomsRoomEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
